log:
  Level: info
  Format: json #  text is another value supported
  Output: stdout # stdout or file
  File:
    Filename: "airdb.log"
    MaxSize: 4024
    Compress: true
    MaxBackups: 5
    MaxAge: 5

grpc:
  port: 50051


dbOptions:
  dbPath: "/home/sohanvir/softwares/go/src/github.com/dailyhunt/airdb/adb"


